version: '3.8'
services:
  java-app:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      my-network:
    container_name: java-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-server:5432/financialmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./:/app
    depends_on:
      - db-server

  db-server:
    image: postgres:latest
    container_name: db-server
    ports:
      - "3306:3306"
      - "5433:5432"
    networks:
      my-network:
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=financialmanagement
    volumes:
      - postgres_data:/var/lib/mysql
      - postgres_config:/etc/mysql/conf.d
volumes:
  postgres_data:
  postgres_config:

networks:
  my-network: