name: Java CI

on: [push, pull_request]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build the docker-compose
        run: docker-compose up -d
        
      - name: Run docker log
        run: docker logs java-app

