name: Java CI

on: [push, pull_request]
      
jobs:
  compose-container:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Build compose file
        run: docker-compose up -d --build
        
